Customer/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    # user urls

    # path("", index, name="index"),
    path("user_login", user_login, name="user_login"),
    path("add_user", add_user, name="add_user"),
    path("login", login, name="login"),
    path("user_logout", user_logout, name="user_logout"),
    path("", view, name="view"),
    path("viewProductByCategory/<int:id>", viewProductByCategory, name="viewProductByCategory"),
    path("searchproducts", searchproducts, name="searchproducts"),
    path("productdetails/<int:id>", productdetails, name="productdetails"),
    path("saveProductToCart", saveProductToCart, name="saveProductToCart"),
    path("contact_us", contact_us, name="contact_us"),
    path("about_us", about_us, name="about_us"),
    path("wishlist/<int:id>", wishlist, name="wishlist"),
    path("shopping_cart/<int:id>", shopping_cart, name="shopping_cart"),
    path("add_to_cart", add_to_cart, name="add_to_cart"),
    path("changecart_quantity/<int:id>", changecart_quantity, name='changecart_quantity'),
    path("delete_cart/<int:id>", delete_cart, name='delete_cart'),
    path("ConfirmOrder", ConfirmOrder, name="ConfirmOrder"),
    path("dashboard", dashboard, name="dashboard"),
    path("billdetails/<int:id>", billdetails, name="billdetails"),
    path("updateprofile", updateprofile, name="updateprofile"),
    path("changeClientPassword", changeClientPassword, name="changeClientPassword"),

]

GroceryMart/urls.py
from django.contrib import admin
from django.urls import *
from django.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Merchant/", include('Merchant.urls')),
    path("", include('Customer.urls')),
]

Customer/models.py
from django.db import models
from Merchant.models import *


# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    dob = models.DateField()
    mobile = models.IntegerField()
    password = models.CharField(max_length=255)
    address = models.TextField()
    city = models.CharField(max_length=255)

    class Meta:
        db_table = 'client'

    def __str__(self):
        return self.name


class Cart(models.Model):
    quantity = models.FloatField()
    total_price = models.FloatField()
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE)
    client = models.ForeignKey(to=Client, on_delete=models.CASCADE)

    class Meta:
        db_table = 'addtocart'


class Bill(models.Model):
    totalprice = models.FloatField()
    totalitems = models.FloatField()
    billdate = models.DateField()
    billtime = models.TimeField()
    paymentstatus = models.CharField(max_length=1, choices=(("p", "pending"), ("c", "completed")), default='p')
    Client = models.ForeignKey(to=Client, on_delete=models.CASCADE)

    class Meta:
        db_table = 'bill'


class Billdetail(models.Model):
    itemprice = models.FloatField()
    quantity = models.FloatField()
    Product = models.ForeignKey(to=Products, on_delete=models.CASCADE)
    Bill = models.ForeignKey(to=Bill, on_delete=models.CASCADE)
    Client = models.ForeignKey(to=Client, on_delete=models.CASCADE)

    class Meta:
        db_table = 'billdetail'

Merchant/models.py
from django.db import models


# Create your models here.

class Merchant(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    mobile = models.CharField(max_length=20)
    password = models.CharField(max_length=255)
    shop_name = models.CharField(max_length=255)
    address = models.TextField()
    city = models.CharField(max_length=255)

    class Meta:
        db_table = 'Merchant'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()

    class Meta:
        db_table = 'category'

        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField(max_length=20)
    discount = models.IntegerField()
    image = models.FileField(upload_to='products/')

    Merchant = models.ForeignKey(to=Merchant, on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'products'
        verbose_name_plural = 'products'

templates/addcategory.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Category</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="row">
            <div class="col-sm-8 offset-sm-2">
                <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for i in form %}
                        <div class="mb-3">
                            {{ i.label_tag }}
                            {{ i }}

                        </div>

                    {% endfor %}

                    <div class="text-center">
                        <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/contact_us.html
{% extends 'merchantlayout/layout.html' %}

{% block customercontent %}
    <main>
        <!-- Breadcrumb Start -->
        <section class="breadcrumb-section">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-content">
                            <h1 class="page-title">Contact Us</h1>
                            <ul class="breadcrumb-page-list">
                                <li class="breadcrumb-item"><a href="viewproducts">Home</a></li>
                                <li class="breadcrumb-item">Contact Us</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Breadcrumb End -->

        <!-- Page Section Content Start -->
        <section class="page-secton-wrapper section-space-ptb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-us-area">
                            <h2 class="fw-bold mb-3">Let us know how we can help</h2>
                            <p class="text me-lg-4">Please contact us using the below options. For fastest reply, please
                                include your name, organization, appropriate contact information and a brief summary of
                                your
                                inquiry.</p>
                            <ul class="mt-5">
                                <li class="contact-feature-item">
                                    <div class="contact-feature-icon">
                                        <i class="icon-rt-location-pin"></i>
                                    </div>
                                    <div class="contact-feature-content">
                                        <h5 class="contact-feature-title fw-bold mb-1">
                                            Office Location
                                        </h5>
                                        <p class="text">I.K.G Punjab Technical University, Campus - Amritsar</p>
                                    </div>
                                </li>
                                <li class="contact-feature-item">
                                    <div class="contact-feature-icon feature-icon-2">
                                        <i class="icon-rt-phone-volume-solid"></i>
                                    </div>
                                    <div class="contact-feature-content">
                                        <h5 class="contact-feature-title fw-bold mb-1">
                                            Call us anytime
                                        </h5>
                                        <p class="text">For immediate help please call <br>
                                            +91 6283160903, +91 6280699184</p>
                                    </div>
                                </li>
                                <li class="contact-feature-item">
                                    <div class="contact-feature-icon feature-icon-3">
                                        <i class="icon-rt-mail-outline"></i>
                                    </div>
                                    <div class="contact-feature-content">
                                        <h5 class="contact-feature-title fw-bold mb-1">
                                            Send Mail
                                        </h5>
                                        <p class="text">
                                            <a href="#">grocerymart@gmail.com</a>
                                            <br>
                                            <a href="#">grocerymart@gmail.com</a>
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="contact-us-form-wrap">
                            <form id="#contact-form" action="#"
                                  method="post">
                                <div class="single-input-box">
                                    <input type="text" placeholder="Name *" name="con_name" required>
                                </div>
                                <div class="single-input-box">
                                    <input type="email" placeholder="Email *" name="con_email" required>
                                </div>
                                <div class="single-input-box">
                                    <input type="text" placeholder="Phone" name="con_phone">
                                </div>
                                <div class="single-input-box">
                                    <textarea placeholder="Message *" name="con_message" required></textarea>
                                </div>
                                <div class="single-input-box">
                                    <button type="submit" class="btn btn--primary">Send Message</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Section Content End -->

        <!-- Google map start -->
        <div class="ifram-map-wrapper">
            <iframe class="ifram-map"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3743278.227637299!2d-61.159056951307704!3d-2.371597134950372!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91e8605342744385%3A0x3d3c6dc1394a7fc7!2sAmazon%20Rainforest!5e0!3m2!1sen!2sbd!4v1638433670177!5m2!1sen!2sbd"
                    allowfullscreen="" loading="lazy"></iframe>
        </div>
        <!-- Google map end -->

    </main>
{% endblock %}

templates/dashboard.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container my-4">
        <h2 class="text-center">View Purchased Products</h2>
        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Date</th>
                <th>Time</th>
                <th>Image</th>
            </tr>
            </thead>

            <tbody>
            {% for i in detailObj %}

                <tr>
                    <td>{{ i.Product.name }}</td>
                    <td>{{ i.quantity }}</td>
                    <td>{{ i.itemprice }}</td>
                    <td>{{ i.Bill.billdate }}</td>
                    <td>{{ i.Bill.billtime }}</td>
                    <td><img src="/static/media/{{ i.Product.image }}" alt="" width="70"></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div></div>
{% endblock %}

templates/deleteitems.html
{% extends 'merchantlayout/layout.html' %}
{% load  static %}
{% block customercontent %}
    <div class="container">
        <form action="/delete_product/{{ product.id }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_name">Name:</label>
                <input type="text" name="name" value="{{ product.name }}" class="form-control" maxlength="255"
                       required="" id="id_name">

            </div>


            <div class="mb-3">
                <label for="id_description">Description:</label>
                <input type="text" name="description" value="{{ product.description }}" class="form-control" required="" id="id_description">

            </div>


            <div class="mb-3">
                <label for="id_price">Price:</label>
                <input type="text" name="price" value="{{ product.price }}" class="form-control" required="" id="id_price">

            </div>


            <div class="mb-3">
                <label for="id_discount">Discount:</label>
                <input type="text" name="discount" value="{{ product.discount }}" class="form-control" required="" id="id_discount">

            </div>

            <div class="col-sm-8 img-fluid">
                <img src="/static/media/{{ product.image }}" alt="">
            </div>
            <div class="mb-3">
                <label for="id_image">Image:</label>
                <input type="file" name="image" class="form-control" id="id_image">

            </div>


            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

            </div>

        </form>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>pageTitle</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        {% if request.session.merchant %}
            <a class="navbar-brand" href="{% url 'merchant_login' %}">{{ request.session.merchant.name }}</a>

        {% endif %}
        <a class="navbar-brand" href="{% url 'merchant_login' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse position-relative" id="navbarNavDropdown">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link active" href="#">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">About Us</a>
                </li>


                {% if request.session.merchant %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Products
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'products' %}">Add Products</a></li>
                            <li><a class="dropdown-item" href="{% url 'viewproducts' %}">View Products</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'addcategory' %}">Add Category</a></li>
                            <li><a class="dropdown-item" href="{% url 'viewcategory' %}">View Category</a></li>
                        </ul>
                    </li>
                    <li class="nav-item position-absolute top-0 end-0">
                        <a class="btn btn-danger" href="{% url 'merchant_logout' %}">Log Out</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
{% block maincontent %}

{% endblock %}

</body>
</html>

templates/merchant_login.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}
{% block customercontent %}


    <div class="row">
        <h1 class="text-center text-primary my-2">Merchant Registration and Login</h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="col-sm-5 my-3 offset-1">
            <form action="/Merchant/register_merchant" method="post">
                {% csrf_token %}

                <h2 class="text-center text-primary">Register</h2>
                <div>
                    <label for="name">ENTER FULL NAME</label>
                    <input type="text" name="name" id="name" class="form-control my-2">
                </div>

                <div>
                    <label for="email">ENTER EMAIL</label>
                    <input type="text" name="email" id="email" class="form-control my-2">
                </div>
                <div>
                    <label for="mobile">ENTER MOBILE</label>
                    <input type="tel" name="mobile" id="mobile" class="form-control my-2">
                </div>
                <div>
                    <label for="password">ENTER PASSWORD</label>
                    <input type="password" name="password" id="password" class="form-control my-2">
                </div>
                <div>
                    <label for="shop_name">ENTER SHOP NAME</label>
                    <input type="text" name="shop_name" id="shop_name" class="form-control my-2">
                </div>
                <div>
                    <label for="address">ADDRESS</label>
                    <textarea name="address" id="address" cols="30" rows="3" class="form-control my-2"></textarea>
                </div>
                <div>
                    <label for="city">ENTER CITY</label>
                    <input type="text" name="city" id="city" class="form-control my-2">
                </div>
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">
                </div>

            </form>
        </div>
        <div class="col-sm-5 my-3">
            <form action="/Merchant/login" method="post">
                {% csrf_token %}

                <h2 class="text-center text-primary">Login</h2>
                <div>
                    <label for="email">ENTER EMAIL</label>
                    <input type="email" name="email" id="email" class="form-control my-2">
                </div>
                <div>
                    <label for="password">ENTER PASSWORD</label>
                    <input type="password" id="password" name="password" class="form-control my-2">
                </div>
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">
                </div>


            </form>
        </div>


    </div>





{% endblock %}

templates/products.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Products</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="row">
            <div class="col-sm-8 offset-sm-2">
                <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for i in forms %}
                        <div class="mb-3">
                            {{ i.label_tag }}
                            {{ i }}

                        </div>

                    {% endfor %}
                    <input type="hidden" id="merchant" name="Merchant_id" value="{{ request.session.merchant.id }}">
                    <div class="text-center">
                        <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                    </div>

                </form>
            </div>
        </div>


    </div>
{% endblock %}

templates/updatecategory.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Category</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}</div>

                <button type="button" class="btn-close" data-bs-dismiss=" alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for i in form %}
                    <div class="mb-3">
                        {{ i.label_tag }}
                        {{ i }}

                    </div>

                {% endfor %}

                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/updateitems.html
{% extends 'merchantlayout/layout.html' %}
{% load  static %}
{% block customercontent %}
    <div class="container">
        <form action="/Merchant/saveupdate/{{ product.id }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_name">Name:</label>
                <input type="text" name="name" value="{{ product.name }}" class="form-control" maxlength="255"
                       required="" id="id_name">

            </div>


            <div class="mb-3">
                <label for="id_description">Description:</label>
                <input type="text" name="description" value="{{ product.description }}" class="form-control" required="" id="id_description">

            </div>


            <div class="mb-3">
                <label for="id_price">Price:</label>
                <input type="text" name="price" value="{{ product.price }}" class="form-control" required="" id="id_price">

            </div>


            <div class="mb-3">
                <label for="id_discount">Discount:</label>
                <input type="text" name="discount" value="{{ product.discount }}" class="form-control" required="" id="id_discount">

            </div>

            <div class="col-sm-8 img-fluid">
                <img src="/static/media/{{ product.image }}" alt="">
            </div>
            <div class="mb-3">
                <label for="id_image">Image:</label>
                <input type="file" name="image" class="form-control" id="id_image">

            </div>


            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

            </div>

        </form>
    </div>
{% endblock %}

templates/updateprofile.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="row">
        <h1 class="text-center text-success my-3">Update Merchant Profile</h1>
        <div class="col-sm-5 offset-1">
            <h3 class="text-center text-success mb-2">My Profile</h3>
            <form action="updateprofile" id="profile_form_area" method="post">
                {% csrf_token %}
                <div>
                    <label for="name">Name</label>
                    <input type="text" class="form-control my-2" id="name" name="name" value="{{ profile.name }}">
                </div>

                <div>
                    <label for="email">Email address</label>
                    <input type="text" class="form-control my-2" id="email" name="email" value="{{ profile.email }}">
                </div>
                <div>
                    <label for="mobile">Mobile number</label>
                    <input type="text" class="form-control my-2" id="mobile" name="mobile"
                           value="{{ profile.mobile }}">
                </div>
                <div>
                    <label for="shop_name">Shop Name</label>
                    <input type="text" class="form-control my-2" id="shop_name" name="shop_name"
                           value="{{ profile.shop_name }}">
                </div>
                <div>
                    <label for="address">Address</label>
                    <textarea class="form-control" name="address" id="address" cols="30"
                              rows="3"> {{ profile.address }}</textarea>
                </div>
                <div>
                    <label for="city">City</label>
                    <input type="text" class="form-control my-2" id="city" name="city"
                           value="{{ profile.city }}">
                </div>
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                </div>


            </form>
        </div>


        <div class="col-sm-5">
            <form action="changeMerchantPassword" id="profile_form_area"
                  method="post">
                {% csrf_token %}
                <h3 class="text-center text-success">Change password</h3>
                <div>
                    <label class="my-2" for="old-password">OLD PASSWORD</label>

                    <input type="password" class="form-control" name="old-password" id="old-password"
                           placeholder="* * * * * * * * * * * * * * *">
                </div>
                <div>
                    <label class="my-2" for="new-password">NEW PASSWORD</label>
                    <input type="password" class="form-control" name="new-password" id="new-password"
                           placeholder="* * * * * * * * * * * * * * *">
                </div>

                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/viewCategory.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container">
        <h2 class="text-center my-5 text-primary">View Category</h2>

        <table class="table table-hover table-light">
            <thead>
            <tr>

                <th>Name</th>
                <th>Description</th>


            </tr>
            </thead>
            <tbody>
            {% for i in viewcategory %}
                <tr>
                    <td>{{ i.name }}</td>
                    <td>{{ i.desc }}</td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

##testing git

templates/viewProducts.html
{% extends 'merchantlayout/layout.html' %}
{% load static %}

{% block customercontent %}
    <div class="container">
        <h2 class="text-center my-5">View Products</h2>

        <table class="table table-hover table-light">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Merchant ID</th>
                <th>Image</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for i in viewproducts %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.description }}</td>
                    <td>{{ i.price }}</td>
                    <td>{{ i.discount }}</td>
                    <td>{{ i.Merchant_id }}</td>
                    <td>
                        <img src="/static/media/{{ i.image }} " alt="" width="150">
                    </td>
                    <td><a href="update_product/{{ i.id }}" class="btn btn-outline-info">Update</a></td>
                    <td><a href="delete_product/{{ i.id }}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}